- name: configure the backend server
  hosts: backend
  become: yes
  tasks:
    - name: disable nodejs module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present     

    - name: create expense user
      ansible.builtin.user:
        name: expense

    - name: Create a app directory 
      ansible.builtin.file:
        path: /app
        state: directory    

    - name: Download the backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zipf
        dest: /tmp/backend.zip

    - name: Extract backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes     

    - name: install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app      
        
         